UBUNTU: SAUCE: ubuntu_kvm_smoke_test: use trap to do cleanup
If the KVM instance was created but the test did not complete
successfully, the script will terminates with exit 1 before the KVM can
be destroyed.

It is okay on maas-provisioned systems, but on a manual provisioned
instance like our s390x, you will see the following error message when
you try to run this test again:
  uvt-kvm: error: libvirt: storage volume 'bjf-test.qcow' exists already

Add a cleanup function with trap to make sure the KVM will be destroyed
when the script terminates.

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>

diff --git a/ubuntu_kvm_smoke_test/the-test b/ubuntu_kvm_smoke_test/the-test
--- a/ubuntu_kvm_smoke_test/the-test
+++ b/ubuntu_kvm_smoke_test/the-test
@@ -11,12 +11,21 @@ SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogL
 DISTRO="`lsb_release -c | awk '{print$2}'`"
 ARCHITECTURE="$1"
 
+function cleanup {
+    uvt-kvm destroy $SUT
+    # On ppc64el, we need to turn SMT back on after the test.
+    if [ "${ARCHITECTURE}" = "ppc64el" ] ; then
+        sudo ppc64_cpu --smt=on
+    fi
+}
+trap cleanup EXIT
+
 if [ -z "$ARCHITECTURE" ]; then
     echo "** Architecture not specified, please run this script with a given arch."
     exit 1
 fi
 
-# Assume that if kvm-ok fails, we are not suppring kvm on this instance type
+# Assume that if kvm-ok fails, we are not supporting kvm on this instance type
 #
 kvm-ok
 if [ $? != 0 ]; then
@@ -46,10 +55,4 @@ RESULT=`ssh $SSH_OPTIONS ubuntu@\`uvt-kvm ip $SUT\` lsb_release -c | cut -d$'\t'
 if [ "$RESULT" != "$DISTRO" ]; then
     echo "** ERROR: The codename returned from lsb_release -c was (" $RESULT ") and we were expecting '$DISTRO'"
     exit 1
-fi
-uvt-kvm destroy $SUT
-
-# On ppc64el, we need to turn SMT back on after the test.
-if [ "${ARCHITECTURE}" = "ppc64el" ] ; then
-    sudo ppc64_cpu --smt=on
 fi
