UBUNTU SAUCE: kernel-smoke-test-scrub: improve resilvering wait, redux
BugLink: https://bugs.launchpad.net/bugs/1885289

On some slower small memory systems we need to check until resilvering
has completed. The most reliably method is to poll on a scrub until
it finishes successfully. Give up after ~10 minutes and flag a failure
if the scrub can't start or complete successfully.

Signed-off-by: Colin Ian King <colin.king@canonical.com>

diff --git a/ubuntu_zfs_smoke_test/kernel-smoke-test-scrub b/ubuntu_zfs_smoke_test/kernel-smoke-test-scrub
--- a/ubuntu_zfs_smoke_test/kernel-smoke-test-scrub
+++ b/ubuntu_zfs_smoke_test/kernel-smoke-test-scrub
@@ -81,7 +81,6 @@ if [ $ret -ne 0 ]; then
 fi
 
 resilvering=0
-
 #
 # Initial first check
 #
@@ -91,39 +90,26 @@ if [ $n -gt 0 ]; then
 fi
 
 #
-#  Wait a short while for resilvering to kick in
-#
-sleep 5
-
-#
-#  Wait 600 seconds for resilver to complete
+#  ..and do the scrub
 #
 i=0
 while true
 do
-	n=$(zpool status | grep "resilvering" | wc -l)
-	if [ $n -eq 0 ]; then
-		break
-	fi
-	resilvering=1
-	i=$((i + 1))
-	sleep 1
-	if [ $i -gt 600 ]; then
+	(zpool scrub ${POOL}) > /dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		sleep 1
+		i=$((i + 1))
+		sleep 1
+		if [ $i -gt 600 ]; then
+			break
+		fi
+	else
 		break
 	fi
 done
-#
-#  Wait 5 seconds to settle post-scrub
-#
-sleep 5
-
-#
-#  ..and do the scrub
-#
-zpool scrub ${POOL}
-ret=$?
 if [ $ret -ne 0 ]; then
-	echo "FAILED: zpool scrub failed, exit code=$ret"
+	echo "FAILED: zpool scrub failed after $i attempts, exit code=$ret"
 	zpool destroy ${POOL}
 	rm -f ${VDEV0} ${VDEV1} ${VDEV2} ${VDEV3}
 	exit 1
@@ -154,6 +140,7 @@ fi
 
 rm -f ${VDEV0} ${VDEV1} ${VDEV2} ${VDEV3}
 echo "PASSED"
+echo "NOTE: zpool scrub completed after about $i second(s)"
 if [ $resilvering -eq 1 ]; then
 	echo "NOTE: Resilvering detected + completed and srub completed"
 else
